@startuml
left to right direction
actor Passenger
actor AirportStaff
actor CabinCrew
actor Security
actor BaggageHandler
actor Mechanic
rectangle System {
usecase BoardAircraft
usecase GoThroughSecurity
usecase FixPlanes
usecase CheckSuspiciousCharactersOut
usecase CheckCCTV
usecase CheckTickets
usecase WeighBags
usecase PutBagsOnThePlane
usecase ServeFoodToPassengers
usecase MakeSurePassengersAreSeated
Passenger --> BoardAircraft
Passenger --> GoThroughSecurity
Mechanic --> FixPlanes
Security --> CheckSuspiciousCharactersOut
Security --> CheckCCTV
AirportStaff --> CheckTickets
AirportStaff --> WeighBags
BaggageHandler --> PutBagsOnThePlane
CabinCrew --> ServeFoodToPassengers
CabinCrew --> MakeSurePassengersAreSeated
}
@enduml