@startuml

title Register user

actor User
participant ScooterHireApp
participant ScooterHireBackendAPI
participant RegisteredUser
database ScooterHireDatabase
actor DVLA_API

User -> ScooterHireApp: registerDetails(name,age, bank details, driving lisence etc)
User <- ScooterHireApp: successfulRegistration
ScooterHireApp -> ScooterHireBackendAPI: registerDetails(name,age, bank details, driving lisence etc)
ScooterHireBackendAPI -> RegisteredUser: new(name, driving lisence, etc..)
ScooterHireBackendAPI -> ScooterHireDatabase: checkIfUserIsRegistered
ScooterHireBackendAPI -> DVLA_API: checkDrivingLisence
ScooterHireBackendAPI -> ScooterHireDatabase: save(registeredUser)

@enduml