@startuml

actor User
participant ScooterHireApp
actor Scooter
participant ScooterHireBackendAPI
participant HireTransaction
database ScooterHireDatabase
actor ChargingStation

User -> ScooterHireApp: requestHire
User -> Scooter: scanQRCode
ScooterHireApp -> ScooterHireBackendAPI: startHire(scooterID)
ScooterHireApp -> ChargingStation: releaseScooter
ScooterHireBackendAPI -> HireTransaction: create(userName, scooterID)
ChargingStation -> ChargingStation: releaseScooter
ScooterHireBackendAPI -> Scooter: isCharged
ScooterHireBckendAPI -> Scooter: currentMileage

@enduml