
title Electric Scoter Hire - Class Diagram


class Scooter {
    - QRCode
    - Indicators
    - Status 
    - Speedometer
    - Tyres
    - MaxSpeed
    - Accelerator
    + charge()
    

}

class RegisteredUser {
    - String userId 
}

class User {

}

class Payment {

}

class ChargingStation {

    + lockedScooter
    + unlockedScooter
}

class HireTransaction {
    - registeredUser
    - distanceTravelled
    - Scooter 
    + getTotalCharge()
}

class MaintenancePerson {
    -employeeID
    + fixScooter()
}

class Person {
    - String: name
}

Scooter <-- User: hire
QRCode <-- User: scan
ChargingStation "1" o-- Scooter
User --|> Person
MaintenancePerson --|> Person
Scooter "1" o-- MaintenancePerson: fix
Scooter "1" o-- QRCode: accept
RegisteredUser --|> Person
Scooter <-- RegisteredUser
QRCode <-- RegisteredUser: scan
HireTransaction "1" o-- Payment: register payment
User --> Payment: pay
RegisteredUser --> Payment: pay


class QRCode {

}




